landing_getting_started_1: |-
  <body>
    <div>
      <div id="searchbox"></div>
      <div id="hits"></div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4"></script>
    <script>
      const search = instantsearch({
        indexName: 'movies',
        searchClient: instantMeiliSearch(
          'http://localhost:7700',
          'searchKey'
        ),
      })

      search.addWidgets([
        instantsearch.widgets.searchBox({
          container: '#searchbox',
        }),
        instantsearch.widgets.hits({
          container: '#hits',
          templates: {
            item: `
              <div>
                <div class="hit-name">
                  {{#helpers.highlight}}{ "attribute": "title" }{{/helpers.highlight}}
                </div>
              </div>
            `,
          },
        }),
      ])
      search.start()
    </script>
  </body>
